# Generated by Django 6.0.6 on 2026-06-23 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choreography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('song_name', models.CharField(max_length=200)),
                ('genre', models.CharField(choices=[('salsa', 'Salsa'), ('bachata', 'Bachata'), ('merengue', 'Merengue'), ('hip_hop', 'Hip-Hop'), ('pop', 'Pop'), ('reggaeton', 'Reggaeton'), ('contemporaneo', 'Contemporáneo')], max_length=20)),
                ('difficulty', models.CharField(choices=[('basic', 'Básico'), ('intermediate', 'Intermedio'), ('advanced', 'Avanzado')], default='basic', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('guest_professor_external', models.CharField(blank=True, max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sales_count', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('pending', 'Pendiente aprobación'), ('published', 'Publicada'), ('rejected', 'Rechazada')], default='draft', max_length=20)),
                ('thumbnail_emoji', models.CharField(default='💃', max_length=10)),
                ('rating', models.DecimalField(decimal_places=1, default=4.5, max_digits=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'choreographies',
                'ordering': ['-sales_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChoreographyVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('video_url', models.URLField(blank=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['part_number'],
            },
        ),
    ]
