# Generated by Django 6.0.6 on 2026-06-23 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('choreographies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='choreography',
            name='guest_professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='choreographies_guest', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='choreography',
            name='main_professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='choreographies_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='choreographyvideo',
            name='choreography',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='choreographies.choreography'),
        ),
        migrations.AlterUniqueTogether(
            name='choreographyvideo',
            unique_together={('choreography', 'part_number')},
        ),
    ]
