# Generated by Django 6.0.6 on 2026-06-25 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choreographies', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choreography',
            name='sales_count',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Calculado automáticamente a partir de ventas completadas.'),
        ),
    ]
